// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsvUPhPC3F6BSg8CX_tZMeecXBp_sKsxY',
    appId: '1:838252172667:web:a67f3fac4f92131cdfd9de',
    messagingSenderId: '838252172667',
    projectId: 'papa-e3194',
    authDomain: 'papa-e3194.firebaseapp.com',
    storageBucket: 'papa-e3194.appspot.com',
    measurementId: 'G-QDBBP9840D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxIYjbj7J7wfnY0lrEr3UEzg_npyNPltg',
    appId: '1:838252172667:android:bd2160f56b8d3ef1dfd9de',
    messagingSenderId: '838252172667',
    projectId: 'papa-e3194',
    storageBucket: 'papa-e3194.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFcWARtCS9PEA0nnxz7R6fnCNW89h7ljw',
    appId: '1:838252172667:ios:e3adaf8abc2d3a04dfd9de',
    messagingSenderId: '838252172667',
    projectId: 'papa-e3194',
    storageBucket: 'papa-e3194.appspot.com',
    iosClientId: '838252172667-mstlfj8evcs6emmsjsbrec8hnds0jqt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFcWARtCS9PEA0nnxz7R6fnCNW89h7ljw',
    appId: '1:838252172667:ios:e3adaf8abc2d3a04dfd9de',
    messagingSenderId: '838252172667',
    projectId: 'papa-e3194',
    storageBucket: 'papa-e3194.appspot.com',
    iosClientId: '838252172667-mstlfj8evcs6emmsjsbrec8hnds0jqt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychatApp',
  );
}
